# Generated by Django 4.0.6 on 2022-11-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientadminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('sessionid', models.CharField(max_length=255)),
                ('alldata', models.TextField()),
            ],
            options={
                'db_table': 'UserData',
            },
        ),
    ]
