# Generated by Django 4.0.6 on 2022-12-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientadminapp', '0002_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('member_code', models.CharField(max_length=255)),
                ('member_details', models.CharField(max_length=255)),
                ('member_u_code', models.CharField(max_length=255)),
                ('member_spec', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Guests',
            },
        ),
        migrations.CreateModel(
            name='Level1Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=255)),
                ('item_details', models.CharField(max_length=255)),
                ('item_u_code', models.CharField(max_length=255)),
                ('item_spec', models.CharField(max_length=255)),
                ('barcode', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Level1Items',
            },
        ),
        migrations.CreateModel(
            name='Level2Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=255)),
                ('item_details', models.CharField(max_length=255)),
                ('item_u_code', models.CharField(max_length=255)),
                ('item_spec', models.CharField(max_length=255)),
                ('barcode', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Level2Items',
            },
        ),
        migrations.CreateModel(
            name='Level3Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=255)),
                ('item_details', models.CharField(max_length=255)),
                ('item_u_code', models.CharField(max_length=255)),
                ('item_spec', models.CharField(max_length=255)),
                ('barcode', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Level3Items',
            },
        ),
        migrations.CreateModel(
            name='Level4Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=255)),
                ('item_details', models.CharField(max_length=255)),
                ('item_u_code', models.CharField(max_length=255)),
                ('item_spec', models.CharField(max_length=255)),
                ('barcode', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Level4Items',
            },
        ),
        migrations.CreateModel(
            name='Level5Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=255)),
                ('item_details', models.CharField(max_length=255)),
                ('item_u_code', models.CharField(max_length=255)),
                ('item_spec', models.CharField(max_length=255)),
                ('barcode', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Level5Items',
            },
        ),
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('membertype', models.CharField(max_length=255)),
                ('member', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('datatype', models.CharField(max_length=255)),
                ('operationalrights', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('portfolio_name', models.CharField(max_length=255)),
                ('portfolio_code', models.CharField(max_length=255)),
                ('portfolio_details', models.CharField(max_length=255)),
                ('portfolio_u_code', models.CharField(max_length=255)),
                ('portfolio_spec', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Rights',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('level1', models.CharField(max_length=255)),
                ('level2', models.CharField(max_length=255)),
                ('level3', models.CharField(max_length=255)),
                ('level4', models.CharField(max_length=255)),
                ('level5', models.CharField(max_length=255)),
                ('security_layer', models.CharField(max_length=255)),
                ('role_name', models.CharField(max_length=255)),
                ('role_code', models.CharField(max_length=255)),
                ('role_details', models.CharField(max_length=255)),
                ('role_u_code', models.CharField(max_length=255)),
                ('role_spec', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('member_code', models.CharField(max_length=255)),
                ('member_details', models.CharField(max_length=255)),
                ('member_u_code', models.CharField(max_length=255)),
                ('member_spec', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'TeamMembers',
            },
        ),
    ]
