# Generated by Django 4.0.6 on 2022-12-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientadminapp', '0003_guests_level1items_level2items_level3items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='publiclink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('linkcode', models.CharField(max_length=255)),
                ('dateof', models.CharField(max_length=255)),
                ('other', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'publiclink',
            },
        ),
    ]
