# Generated by Django 4.0.6 on 2022-12-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientadminapp', '0004_publiclink'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiclink',
            name='org',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publiclink',
            name='dateof',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publiclink',
            name='linkcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publiclink',
            name='other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
