# Generated by Django 4.0.6 on 2022-12-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientadminapp', '0005_publiclink_org_alter_publiclink_dateof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiclink',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
