# Generated by Django 4.0.6 on 2022-12-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientadminapp', '0006_publiclink_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiclink',
            name='linkstatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publiclink',
            name='productstatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publiclink',
            name='qrcodeid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
