# Generated by Django 4.0.6 on 2023-01-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientadminapp', '0007_publiclink_linkstatus_publiclink_productstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiclink',
            name='portfolio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publiclink',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publiclink',
            name='qrpath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
