# Generated by Django 4.0.4 on 2022-12-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAdmin',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('profile', models.TextField()),
                ('organisations', models.TextField()),
                ('products', models.TextField()),
                ('members', models.TextField()),
                ('portfolio', models.TextField()),
                ('security_layers', models.TextField()),
                ('location', models.TextField()),
                ('other_organisation', models.TextField()),
            ],
        ),
    ]
