# Generated by Django 4.0.4 on 2022-12-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_admin_new', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientadmin',
            name='location',
        ),
        migrations.AddField(
            model_name='clientadmin',
            name='document_name',
            field=models.CharField(default='Jazz3650', max_length=20),
            preserve_default=False,
        ),
    ]
